Add Travis and Coala for code linting

diff --git a/templates/postgres.template.yml b/templates/postgres.template.yml
--- a/templates/postgres.template.yml
+++ b/templates/postgres.template.yml
@@ -15,9 +15,9 @@ params:
 hooks:
   before_code:
     - replace:
-       filename: /etc/service/unicorn/run
-       from: "# postgres"
-       to: sv start postgres || exit 1
+        filename: /etc/service/unicorn/run
+        from: "# postgres"
+        to: sv start postgres || exit 1
 
 run:
   - exec: mkdir -p /shared/postgres_run
@@ -31,103 +31,103 @@ run:
   - exec: mkdir -p /shared/postgres_run/9.5-main.pg_stat_tmp
   - exec: chown postgres:postgres /shared/postgres_run/9.5-main.pg_stat_tmp
   - file:
-     path: /etc/service/postgres/run
-     chmod: "+x"
-     contents: |
+      path: /etc/service/postgres/run
+      chmod: "+x"
+      contents: |
         #!/bin/sh
         exec 2>&1
         echo -1000 >/proc/self/oom_score_adj
         HOME=/var/lib/postgresql USER=postgres exec chpst -u postgres:postgres:ssl-cert -U postgres:postgres:ssl-cert /usr/lib/postgresql/9.5/bin/postmaster -D /etc/postgresql/9.5/main
 
   - file:
-     path: /etc/runit/3.d/99-postgres
-     chmod: "+x"
-     contents: |
+      path: /etc/runit/3.d/99-postgres
+      chmod: "+x"
+      contents: |
        #!/bin/bash
        sv stop postgres
 
   - file:
-     path: /root/upgrade_postgres
-     chmod: "+x"
-     contents: |
-       #!/bin/bash
-       PG_MAJOR_OLD=`cat /shared/postgres_data/PG_VERSION`
+      path: /root/upgrade_postgres
+      chmod: "+x"
+      contents: |
+        #!/bin/bash
+        PG_MAJOR_OLD=`cat /shared/postgres_data/PG_VERSION`
 
-       if [ ! "9.5" = "$PG_MAJOR_OLD" ]; then
-         echo Upgrading PostgreSQL to from version ${PG_MAJOR_OLD} to 9.5
-         rm -fr /shared/postgres_data_new
-         install -d -m 0755 -o postgres -g postgres /shared/postgres_data_new && sudo -u postgres /usr/lib/postgresql/9.5/bin/initdb -D /shared/postgres_data_new || exit 0
-         apt-get update
-         apt-get install -y postgresql-${PG_MAJOR_OLD}
-         /etc/init.d/postgresql stop
-         rm -fr /shared/postgres_data/postmaster.pid
-         cd ~postgres
-         cp /etc/postgresql/${PG_MAJOR_OLD}/main/*.conf /shared/postgres_data
-         echo  >> /shared/postgres_data/postgresql.conf
-         echo "data_directory = '/shared/postgres_data'" >> /shared/postgres_data/postgresql.conf
-         SUCCESS=true
-         sudo -u postgres /usr/lib/postgresql/9.5/bin/pg_upgrade -d /shared/postgres_data -D /shared/postgres_data_new -b /usr/lib/postgresql/${PG_MAJOR_OLD}/bin -B /usr/lib/postgresql/9.5/bin || SUCCESS=false
+        if [ ! "9.5" = "$PG_MAJOR_OLD" ]; then
+          echo Upgrading PostgreSQL to from version ${PG_MAJOR_OLD} to 9.5
+          rm -fr /shared/postgres_data_new
+          install -d -m 0755 -o postgres -g postgres /shared/postgres_data_new && sudo -u postgres /usr/lib/postgresql/9.5/bin/initdb -D /shared/postgres_data_new || exit 0
+          apt-get update
+          apt-get install -y postgresql-${PG_MAJOR_OLD}
+          /etc/init.d/postgresql stop
+          rm -fr /shared/postgres_data/postmaster.pid
+          cd ~postgres
+          cp /etc/postgresql/${PG_MAJOR_OLD}/main/*.conf /shared/postgres_data
+          echo  >> /shared/postgres_data/postgresql.conf
+          echo "data_directory = '/shared/postgres_data'" >> /shared/postgres_data/postgresql.conf
+          SUCCESS=true
+          sudo -u postgres /usr/lib/postgresql/9.5/bin/pg_upgrade -d /shared/postgres_data -D /shared/postgres_data_new -b /usr/lib/postgresql/${PG_MAJOR_OLD}/bin -B /usr/lib/postgresql/9.5/bin || SUCCESS=false
 
-         if [[ "$SUCCESS" == 'false' ]]; then
-           echo -------------------------------------------------------------------------------------
-           echo UPGRADE OF POSTGRES FAILED
-           echo
-           echo You are going to need to export your data and import into a clean instance:
-           echo
+          if [[ "$SUCCESS" == 'false' ]]; then
+            echo -------------------------------------------------------------------------------------
+            echo UPGRADE OF POSTGRES FAILED
+            echo
+            echo You are going to need to export your data and import into a clean instance:
+            echo
 
-           if [ "$PG_MAJOR_OLD" = "9.2" ]; then
-             echo Add the line: 'base_image: "samsaffron/discourse:0.1.1"'
-             echo 'In containers/app.yml: Change "templates/postgres.template.yml" TO "templates/postgres.9.2.template.yml"'
-             echo
-           fi
+            if [ "$PG_MAJOR_OLD" = "9.2" ]; then
+              echo Add the line: 'base_image: "samsaffron/discourse:0.1.1"'
+              echo 'In containers/app.yml: Change "templates/postgres.template.yml" TO "templates/postgres.9.2.template.yml"'
+              echo
+            fi
 
-           if [ "$PG_MAJOR_OLD" = "9.3" ]; then
-             echo 'In containers/app.yml: Change "templates/postgres.template.yml" TO "templates/postgres.9.3.template.yml"'
-             echo
-           fi
+            if [ "$PG_MAJOR_OLD" = "9.3" ]; then
+              echo 'In containers/app.yml: Change "templates/postgres.template.yml" TO "templates/postgres.9.3.template.yml"'
+              echo
+            fi
 
-           echo Run "./launcher rebuild app" again
-           echo
-           echo When your instance is running:
-           echo Run "./launcher enter app"
-           echo Run "cd /shared/postgres_backup && sudo -u postgres pg_dump discourse > backup.db"
-           echo
-           if [ "$PG_MAJOR_OLD" = "9.2" ]; then
-             echo Undo the base_image in your container config
-           fi
-           if [ "$PG_MAJOR_OLD" = "9.3" ]; then
-             echo Undo the postgres template in your container config
-           fi
-           echo Run: "./launcher stop app"
-           echo Run: "sudo mv /var/discourse/shared/standalone/postgres_data /var/discourse/shared/standalone/postgres_data_old"
-           echo Run: "./launcher rebuild app"
-           echo
-           echo Run: "./launcher enter app"
-           echo Run: "cd /shared/postgres_backup"
-           echo Run: "sv stop unicorn"
-           echo Run: "sudo -iu postgres dropdb discourse"
-           echo Run: "sudo -iu postgres createdb discourse"
-           echo Run: "sudo -iu postgres psql discourse < backup.db"
-           echo Run: "exit"
-           echo Run: "./launcher rebuild app"
-           exit 1
-         fi
+            echo Run "./launcher rebuild app" again
+            echo
+            echo When your instance is running:
+            echo Run "./launcher enter app"
+            echo Run "cd /shared/postgres_backup && sudo -u postgres pg_dump discourse > backup.db"
+            echo
+            if [ "$PG_MAJOR_OLD" = "9.2" ]; then
+              echo Undo the base_image in your container config
+            fi
+            if [ "$PG_MAJOR_OLD" = "9.3" ]; then
+              echo Undo the postgres template in your container config
+            fi
+            echo Run: "./launcher stop app"
+            echo Run: "sudo mv /var/discourse/shared/standalone/postgres_data /var/discourse/shared/standalone/postgres_data_old"
+            echo Run: "./launcher rebuild app"
+            echo
+            echo Run: "./launcher enter app"
+            echo Run: "cd /shared/postgres_backup"
+            echo Run: "sv stop unicorn"
+            echo Run: "sudo -iu postgres dropdb discourse"
+            echo Run: "sudo -iu postgres createdb discourse"
+            echo Run: "sudo -iu postgres psql discourse < backup.db"
+            echo Run: "exit"
+            echo Run: "./launcher rebuild app"
+            exit 1
+          fi
 
-         mv /shared/postgres_data /shared/postgres_data_old
-         mv /shared/postgres_data_new /shared/postgres_data
+          mv /shared/postgres_data /shared/postgres_data_old
+          mv /shared/postgres_data_new /shared/postgres_data
 
-         echo -------------------------------------------------------------------------------------
-         echo UPGRADE OF POSTGRES COMPLETE
-         echo
-         echo Old ${PG_MAJOR_OLD} database is stored at /shared/postgres_data_old
-         echo
-         echo To complete the upgrade, rebuild again using:
-         echo
-         echo     ./launcher rebuild app
-         echo -------------------------------------------------------------------------------------
-         # Magic exit status to denote no failure
-         exit 77
-       fi
+          echo -------------------------------------------------------------------------------------
+          echo UPGRADE OF POSTGRES COMPLETE
+          echo
+          echo Old ${PG_MAJOR_OLD} database is stored at /shared/postgres_data_old
+          echo
+          echo To complete the upgrade, rebuild again using:
+          echo
+          echo     ./launcher rebuild app
+          echo -------------------------------------------------------------------------------------
+          # Magic exit status to denote no failure
+          exit 77
+        fi
   - exec:
       cmd:
         - chown -R root /var/lib/postgresql/9.5/main
@@ -238,10 +238,10 @@ run:
       raise_on_fail: false
 
   - file:
-     path: /var/lib/postgresql/take-database-backup
-     chown: postgres:postgres
-     chmod: "+x"
-     contents: |
+      path: /var/lib/postgresql/take-database-backup
+      chown: postgres:postgres
+      chmod: "+x"
+      contents: |
         #!/bin/bash
         ID=db-$(date +%F_%T)
         FILENAME=/shared/postgres_backup/$ID.tar.gz
@@ -249,8 +249,8 @@ run:
         echo $FILENAME
 
   - file:
-     path: /var/spool/cron/crontabs/postgres
-     contents: |
+      path: /var/spool/cron/crontabs/postgres
+      contents: |
         # m h  dom mon dow   command
         #MAILTO=?
         #0 */4 * * * /var/lib/postgresql/take-database-backup
